# Le ClusterIssuer utilise la certificat de CA et la clé privée stockés dans root-ca-secret pour générer et signer les nouvelles certificats, y compris les certificats des Ingress dans Kubernetes

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-cluster-issuer
spec:
  ca:
    secretName: root-ca-secret