# Le ClusterIssuer utilise un certificat de CA et sa clé privée pour signer des certificats, y compris des certificats pour des ressources comme les Ingress dans Kubernetes

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-cluster-issuer
spec:
  ca:
    secretName: root-ca-secret