# Le ClusterIssuer utilise un certificat de CA et sa clé privée stockés dans root-ca-secret pour signer les certificats, y compris les certificats des Ingress dans Kubernetes

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-cluster-issuer
spec:
  ca:
    secretName: root-ca-secret