apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chedi-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: chedi-selfsigned-ca
  secretName: root-ca-secret
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to-matching: ca-secret-injection=true
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io