# Ce fichier YAML définit un cluster Elasticsearch avec :
# Un ensemble de 1 nœud maîtres (masters) = master pods, avec 4 Go de mémoire et un stockage de 20 Go par nœud.
# Un ensemble de 1 nœud de données (data)= data pods, avec 8 Go de mémoire et 60 Go de stockage par nœud.

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.17.5
  image: docker.elastic.co/elasticsearch/elasticsearch:8.17.5
  auth:
    fileRealm:
    - secretName: es-user-credentials
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  nodeSets:
    - name: masters
      count: 1
      config:
        node.roles: ["master"]
        node.store.allow_mmap: false
        xpack.security.enabled: true
        xpack.security.authc.token.enabled: true
        xpack.security.authc.api_key.enabled: true
        cluster.routing.allocation.disk.threshold_enabled: false
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 4Gi
                cpu: "2"
              requests:
                memory: 4Gi
                cpu: "1"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: vsphere-csi-sc
    - name: data
      count: 1
      config:
        node.roles: ["data", "ingest"]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 8Gi
                cpu: "2"
              requests:
                memory: 8Gi
                cpu: "1"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 60Gi
          storageClassName: vsphere-csi-sc