apiVersion: v1
kind: Secret
metadata:
  name: es-user-credentials
  namespace: elastic-system
type: kubernetes.io/basic-auth
stringData:
  username: elastic
  password: elastic  # a changer
  roles: superuser,kibana_admin,monitoring_user