# Crée un rôle et l'affecte au elastic-agent, ce role contient les permissions nécessaires pour que l’agent observe et collecte des données sur :
# Les pods, nodes, namespaces, events, services, etc.
# Les ressources dans apps, batch, extensions (comme Deployments, DaemonSets, Jobs, etc.)
# Les métriques (metrics.k8s.io), les logs, la santé des nœuds, etc.
# Les endpoints /metrics, /healthz, etc. (non-resource URLs)

apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: elastic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
  namespace: elastic-system
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  - events
  - services
  - configmaps
  - secrets
  - persistentvolumes
  - persistentvolumeclaims
  - endpoints
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups: ["apps"]
  resources:
  - replicasets
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups: ["extensions"]
  resources:
  - replicasets
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - nodes/proxy
  - nodes/stats
  - nodes/metrics
  - nodes/log
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /healthz
  - /livez
  - /readyz
  - /version
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: elastic-system
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io