apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
# - elastic-agent.rbac.yaml
- elastic.helmrepository.yaml
- eck.helmrelease.yaml
# - elastic-credentials-secret.yaml
# - elasticsearch.config.yaml
# - kibana-instance.yaml
# - kibana.ingress.yaml
# - fleet-server.agent.yaml
# - elastic-kube.agent.yaml
# - elasticsearch.ingress.yaml