apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-release
  namespace: prometheus-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: prometheus.com
            paths:
              - path: /
                pathType: Prefix   
    grafana:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: grafana.com
            paths:
              - path: /
                pathType: Prefix 
    alertmanager:
      service:
        type: NodePort
